/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoia;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JFileChooser;

/**
 *
 * @author carlo
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

        //Lista por columna del archivo csv  
        public ArrayList<String> color = new ArrayList<>();
        public ArrayList<String> director_name = new ArrayList<>();
        public ArrayList<String> num_critic_for_reviews = new ArrayList<>();
        public ArrayList<String> duration = new ArrayList<>();
        public ArrayList<String> director_facebook_likes = new ArrayList<>();
        public ArrayList<String> actor_3_facebook_likes = new ArrayList<>();
        public ArrayList<String> actor_2_name = new ArrayList<>();
        public ArrayList<String> actor_1_facebook_likes = new ArrayList<>();
        public ArrayList<String> gross = new ArrayList<>();
        public ArrayList<String> genres = new ArrayList<>();
            public ArrayList<ArrayList<String>> genres_by_movie = new ArrayList<>();
        public ArrayList<String> actor_1_name = new ArrayList<>();
        public ArrayList<String> movie_title = new ArrayList<>();
        public ArrayList<String> num_voted_users = new ArrayList<>();
        public ArrayList<String> cast_total_facebook_likes = new ArrayList<>();
        public ArrayList<String> actor_3_name = new ArrayList<>();
        public ArrayList<String> facenumber_in_poster = new ArrayList<>();                
        public ArrayList<String> plot_keywords = new ArrayList<>();
        public ArrayList<String> movie_imdb_link = new ArrayList<>();
        public ArrayList<String> num_user_for_reviews = new ArrayList<>();
        public ArrayList<String> language = new ArrayList<>();
        public ArrayList<String> country = new ArrayList<>();                        
        public ArrayList<String> content_rating = new ArrayList<>();
        public ArrayList<String> budget = new ArrayList<>();
        public ArrayList<String> title_year = new ArrayList<>();
        public ArrayList<String> actor_2_facebook_likes = new ArrayList<>();
        public ArrayList<String> imdb_score = new ArrayList<>();
        public ArrayList<String> aspect_ratio = new ArrayList<>();
        public ArrayList<String> movie_facebook_likes = new ArrayList<>();
        
        public int contador = 0;
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnArchivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnArchivo.setText("Open");
        btnArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(btnArchivo)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnArchivo)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //btnArchivo
    private void btnArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(this);
        String ruta = fileChooser.getSelectedFile().getAbsolutePath();   
        
        LeerArchivo(ruta);    
    }//GEN-LAST:event_btnArchivoActionPerformed

    
    //LeerArchivo
    public void LeerArchivo(String ruta){
        int i =0;
        
        try {
            Scanner scanner = new Scanner(new File(ruta));
            while (scanner.hasNextLine()){
                String fila = scanner.nextLine();
                if(i >0){
                LlenarListas(fila);
                }
                i++; 
            }
            scanner.close();
        } catch (FileNotFoundException ex) {
        }
    }
    
   // LlenarListas
   public void LlenarListas(String fila) {
       String valor = "";
       int numeroColumna = 1;

       for (int i = 0; i < fila.length(); i++) {
           String tempo = fila.charAt(i) + "";
           if(!tempo.equals(",")){
             valor += tempo;
           } else {
               /*
               if(valor.equals("")){ 
                   valor = " ";
               }
               */
               String[] genresByMovie;
               ArrayList<String> generos = new ArrayList<>();
               switch(numeroColumna) {
                   case 1: color.add(valor);  
                        break;
                   case 2: director_name.add(valor); 
                        break;
                   case 3: num_critic_for_reviews.add(valor);  
                        break;
                   case 4: duration.add(valor); 
                        break;
                   case 5: director_facebook_likes.add(valor);   
                        break;                   
                   case 6: actor_3_facebook_likes.add(valor); 
                        break;
                   case 7: actor_2_name.add(valor); 
                        break;
                   case 8: actor_1_facebook_likes.add(valor); 
                        break;
                   case 9: gross.add(valor); 
                        break;
                   case 10: genres.add(valor);
                        genresByMovie =  valor.split("\\|");
                        for (String genero : genresByMovie) 
                            generos.add(genero);  
                         genres_by_movie.add(contador, generos); 
                            contador++;
                        break;
                   case 11: actor_1_name.add(valor);  
                        break;
                   case 12: movie_title.add(valor); 
                        break;
                   case 13: num_voted_users.add(valor); 
                        break;
                   case 14: cast_total_facebook_likes.add(valor); 
                        break;
                   case 15: actor_3_name.add(valor);  
                        break;                
                   case 16: facenumber_in_poster.add(valor); 
                        break;
                   case 17: plot_keywords.add(valor); 
                        break;
                   case 18: movie_imdb_link.add(valor); 
                        break;
                   case 19: num_user_for_reviews.add(valor); 
                        break;
                   case 20: language.add(valor);    
                        break;                 
                   case 21: country.add(valor); 
                        break;
                   case 22: content_rating.add(valor); 
                        break;
                   case 23: budget.add(valor); 
                        break;
                   case 24: title_year.add(valor); 
                        break;
                   case 25: actor_2_facebook_likes.add(valor); 
                        break;
                   case 26: imdb_score.add(valor); 
                        break;
                   case 27: aspect_ratio.add(valor);                    
                        break;
                   case 28: 
                       movie_facebook_likes.add(valor);  
                       break;
               }
               numeroColumna++;  
               valor = "";                                                          
           }                                 
        }
   }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArchivo;
    // End of variables declaration//GEN-END:variables
}
