package proyectoia;


import com.sun.glass.events.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author carlo
 */
public class RecomendacionUsuario extends javax.swing.JFrame {

    /**
     * Creates new form RecomendacionUsuario
     */
    public String ruta;
    
    public ArrayList<Double> listaSimilitud = new ArrayList<>();
    public ArrayList<Integer> listaRecomendacion = new ArrayList<>();
    
    public ArrayList<String> lista = new ArrayList<>();
    public boolean flagRecomendar = false;
    
    
    public RecomendacionUsuario(String ruta) {
        this.ruta = ruta;
        initComponents();
    }

    private RecomendacionUsuario() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnRecomendar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        boxAventura = new javax.swing.JCheckBox();
        boxFantasia = new javax.swing.JCheckBox();
        boxDocumental = new javax.swing.JCheckBox();
        boxFiccion = new javax.swing.JCheckBox();
        boxRomance = new javax.swing.JCheckBox();
        boxSuspenso = new javax.swing.JCheckBox();
        boxAnimacion = new javax.swing.JCheckBox();
        boxFamilia = new javax.swing.JCheckBox();
        boxMusical = new javax.swing.JCheckBox();
        boxMisterio = new javax.swing.JCheckBox();
        boxWestern = new javax.swing.JCheckBox();
        boxHistoria = new javax.swing.JCheckBox();
        boxDeporte = new javax.swing.JCheckBox();
        boxCrimen = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        boxHorror = new javax.swing.JCheckBox();
        boxDrama = new javax.swing.JCheckBox();
        boxAccion = new javax.swing.JCheckBox();
        boxComedia = new javax.swing.JCheckBox();
        boxGuerra = new javax.swing.JCheckBox();
        boxBiografia = new javax.swing.JCheckBox();
        boxFilmNoir = new javax.swing.JCheckBox();
        boxGameShow = new javax.swing.JCheckBox();
        boxRealityTV = new javax.swing.JCheckBox();
        boxNews = new javax.swing.JCheckBox();
        boxShort = new javax.swing.JCheckBox();
        boxMusica = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtFieldDirector = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textFieldPais = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textFieldActor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textFieldAñoLanzamiento = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRecomendar.setText("Recomendar");
        btnRecomendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecomendarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList);

        jLabel7.setText("Para alimentar el motor de recomendación y que sus recomendaciones sean más acertadas, usted deberá ingresar los campos que usted quiera");

        jLabel8.setText("Si quiere ingresar más de un elemento en un campo puede hacerlo seguido de una coma");

        jButton1.setText("Nueva Recomendación");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        boxAventura.setText("Aventura");

        boxFantasia.setText("Fantasía");

        boxDocumental.setText("Documental");

        boxFiccion.setText("Ciencia Ficción");

        boxRomance.setText("Romance");

        boxSuspenso.setText("Suspenso");

        boxAnimacion.setText("Animación");

        boxFamilia.setText("Familia");

        boxMusical.setText("Musical");

        boxMisterio.setText("Misterio");

        boxWestern.setText("Western");

        boxHistoria.setText("Historia");

        boxDeporte.setText("Deporte");

        boxCrimen.setText("Crimen");

        jLabel6.setText("Generos:");

        boxHorror.setText("Horror");

        boxDrama.setText("Drama");

        boxAccion.setText("Acción");

        boxComedia.setText("Comedia");

        boxGuerra.setText("Guerra");

        boxBiografia.setText("Biografía");

        boxFilmNoir.setText("Film-Noir");

        boxGameShow.setText("Game-Show");

        boxRealityTV.setText("Reality-TV");

        boxNews.setText("News");

        boxShort.setText("Short");

        boxMusica.setText("Música");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxAventura)
                    .addComponent(boxDocumental)
                    .addComponent(boxDrama)
                    .addComponent(boxAccion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxFantasia)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxFiccion)
                            .addComponent(boxSuspenso)
                            .addComponent(boxRomance))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxMisterio)
                            .addComponent(boxMusical)
                            .addComponent(boxFamilia)
                            .addComponent(boxAnimacion))))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(boxWestern)
                        .addGap(47, 47, 47)
                        .addComponent(boxHorror))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxHistoria)
                            .addComponent(boxDeporte)
                            .addComponent(boxCrimen))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxBiografia)
                            .addComponent(boxGuerra)
                            .addComponent(boxComedia))))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxFilmNoir)
                    .addComponent(boxGameShow)
                    .addComponent(boxRealityTV)
                    .addComponent(boxNews))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxShort)
                    .addComponent(boxMusica))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxAccion)
                    .addComponent(boxFantasia)
                    .addComponent(boxAnimacion)
                    .addComponent(boxWestern)
                    .addComponent(boxHorror)
                    .addComponent(boxFilmNoir)
                    .addComponent(boxShort))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxFiccion)
                    .addComponent(boxAventura)
                    .addComponent(boxFamilia)
                    .addComponent(boxHistoria)
                    .addComponent(boxGuerra)
                    .addComponent(boxGameShow)
                    .addComponent(boxMusica))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxDocumental)
                    .addComponent(boxSuspenso)
                    .addComponent(boxMusical)
                    .addComponent(boxDeporte)
                    .addComponent(boxBiografia)
                    .addComponent(boxRealityTV))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxRomance)
                    .addComponent(boxDrama)
                    .addComponent(boxCrimen)
                    .addComponent(boxComedia)
                    .addComponent(boxMisterio)
                    .addComponent(boxNews))
                .addGap(38, 38, 38))
        );

        jLabel9.setText("Director");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Color", "Black and White" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Actor");

        jLabel4.setText("País");

        jLabel5.setText("Año de Lanzamiento");

        textFieldAñoLanzamiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldAñoLanzamientoKeyTyped(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Spanish", "Japanese", "French", "Mandarin", "Aboriginal", "English", "Hindi", "Russian", "Maya", "Telugu", "Cantonese", "Icelandic", "German", "Aramaic", "Italian", "Dutch", "Hebrew", "Chinese", "Swedish", "Korean", "Thai", "Polish", "Bosnian", "Hungarian", "Portuguese", "Norwegian", "Czech", "Kannada", "Zulu", "Danish", "Arabic", "Dzongkha", "Tamil", "Vietnamese", "Indonesian", "Urdu", "Romanian", "Slovenian", "Dari", "Persian", "None" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel10.setText("(En ingles)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFieldDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textFieldActor, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textFieldPais, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldAñoLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(120, 120, 120))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldActor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textFieldAñoLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel1.setText("Motor de recomendación basado en CONTENT-BASED FILTERING (Item-Based Analysis)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(269, 269, 269)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(btnRecomendar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRecomendar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecomendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecomendarActionPerformed
        // TODO add your handling code here:
        if (flagRecomendar) {
            JOptionPane.showMessageDialog( null, "Para realizar una nueva recomendación ingrese la opción 'Nueva Recomendación'", "ADVERTENCIA",JOptionPane.INFORMATION_MESSAGE);
        } else {

        String director = txtFieldDirector.getText();
        String actor = textFieldActor.getText();
        String genero = "";
        String pais = textFieldPais.getText();
        String año = textFieldAñoLanzamiento.getText();
        //String idioma = textFieldIdioma.getText();
        String color = "";
        String idioma = "";
        /*
        Integer año = 0;
        if (!añoString.isEmpty()) {
             año = Integer.parseInt(textFieldAñoLanzamiento.getText());
        }
        */
        
        color = jComboBox1.getSelectedItem().toString();
        idioma = jComboBox2.getSelectedItem().toString();
        
        if (boxAccion.isSelected()) {
            genero = "Action";
        }
        if (boxAventura.isSelected()) {
            if (!genero.isEmpty()) {
                genero += ",Adventure";
            } else {
                genero = "Adventure";
            }   
        }
        if (boxDocumental.isSelected()) {
            if (!genero.isEmpty()) {
                genero += ",Documentary";
            } else {
                genero = "Documentary";
            }   
        }
        if (boxDrama.isSelected()) {
            if (!genero.isEmpty()) {
                genero += ",Drama";
            } else {
                genero = "Drama";
            }   
        }
        if (boxFantasia.isSelected()) {
            if (!genero.isEmpty()) {
                genero += ",Fantasy";
            } else {
                genero = "Fantasy";
            }   
        }
        if (boxFiccion.isSelected()) {
            if (!genero.isEmpty()) {
                genero += ",Sci-Fi";
            } else {
                genero = "Sci-Fi";
            }   
        }
        if (boxSuspenso.isSelected()) {
            if (!genero.isEmpty()) {
                genero += ",Thriller";
            } else {
                genero = "Thriller";
            }   
        }
        if (boxRomance.isSelected()) {
            if (!genero.isEmpty()) {
                genero += ",Romance";
            } else {
                genero = "Romance";
            }   
        }
        if (boxAnimacion.isSelected()) {
            if (!genero.isEmpty()) {
                genero += ",Animation";
            } else {
                genero = "Animation";
            }   
        }
        if (boxFamilia.isSelected()) {
            if (!genero.isEmpty()) {
                genero += ",Family";
            } else {
                genero = "Family";
            }   
        }
        if (boxMusical.isSelected()) {
            if (!genero.isEmpty()) {
                genero += ",Musical";
            } else {
                genero = "Musical";
            }   
        }
        if (boxMisterio.isSelected()) {
            if (!genero.isEmpty()) {
                genero += ",Mystery";
            } else {
                genero = "Mystery";
            }   
        }
        if (boxWestern.isSelected()) {
            if (!genero.isEmpty()) {
                genero += ",Western";
            } else {
                genero = "Western";
            }   
        }
        if (boxHistoria.isSelected()) {
            if (!genero.isEmpty()) {
                genero += ",History";
            } else {
                genero = "History";
            }   
        }
        if (boxDeporte.isSelected()) {
            if (!genero.isEmpty()) {
                genero += ",Sport";
            } else {
                genero = "Sport";
            }   
        }
        if (boxCrimen.isSelected()) {
            if (!genero.isEmpty()) {
                genero += ",Crime";
            } else {
                genero = "Crime";
            }   
        }
        if (boxHorror.isSelected()) {
            if (!genero.isEmpty()) {
                genero += ",Horror";
            } else {
                genero = "Horror";
            }   
        }
        if (boxGuerra.isSelected()) {
            if (!genero.isEmpty()) {
                genero += ",War";
            } else {
                genero = "War";
            }   
        }
        if (boxBiografia.isSelected()) {
            if (!genero.isEmpty()) {
                genero += ",Biography";
            } else {
                genero = "Biography";
            }   
        }
        if (boxFilmNoir.isSelected()) {
            if (!genero.isEmpty()) {
                genero += ",Fiml-Noir";
            } else {
                genero = "Film-Noir";
            }   
        }
        if (boxGameShow.isSelected()) {
            if (!genero.isEmpty()) {
                genero += ",Game-Show";
            } else {
                genero = "Game-Show";
            }   
        }
        if (boxRealityTV.isSelected()) {
            if (!genero.isEmpty()) {
                genero += ",Reality-TV";
            } else {
                genero = "Reality-TV";
            }   
        }
        if (boxNews.isSelected()) {
            if (!genero.isEmpty()) {
                genero += ",News";
            } else {
                genero = "News";
            }   
        }
        if (boxShort.isSelected()) {
            if (!genero.isEmpty()) {
                genero += ",Short";
            } else {
                genero = "Short";
            }   
        }
        if (boxMusica.isSelected()) {
            if (!genero.isEmpty()) {
                genero += ",Music";
            } else {
                genero = "Music";
            }   
        }
        if (boxComedia.isSelected()) {
            if (!genero.isEmpty()) {
                genero += ",Comedy";
            } else {
                genero = "Comedy";
            }   
        }
        
        DataSetMovies data = new DataSetMovies();
        data.LeerArchivo(ruta);
   
        Similitud(director,actor,genero,pais,año,idioma,color);
        
        int size;
        if (listaRecomendacion.size()>=10) {
            size = 10;
        } else {
            size = listaRecomendacion.size();
        }
        ArrayList<Integer>listaRandom = new ArrayList<>();
        
        for (int i = 0; i < size; i++) {
        Random rand = new Random();
        while(true) 
        {
        int randomElement = listaRecomendacion.get(rand.nextInt(listaRecomendacion.size()));
        if(!listaRandom.contains(randomElement))
        {
        listaRandom.add(randomElement);
        break;
        }
        }
        }
        DefaultListModel model = new DefaultListModel<>();
        for(Integer random : listaRandom) {
            String add = data.movie_title.get(random);
            model.addElement(add);
        }
        DefaultListCellRenderer cellRenderer = (DefaultListCellRenderer)jList.getCellRenderer();
        cellRenderer.setHorizontalAlignment(SwingConstants .CENTER);
        jList.setModel(model);
        
            if (!director.isEmpty()) {
                lista.add("(DIRECTOR)"+director);
            }
            if (!actor.isEmpty()) {
                lista.add("(ACTOR)"+actor);
            }
            if (!genero.isEmpty()) {
                lista.add("(GENERO)"+genero);
            }
            if (!pais.isEmpty()) {
                lista.add("(PAIS)"+pais);
            }
            if (!año.isEmpty()) {
                lista.add("(AÑO)"+año);
            }
            if (!color.isEmpty()) {
                lista.add("(COLOR)"+color);
            }
            if (!idioma.isEmpty()) {
                lista.add("(IDIOMA)"+idioma);
            }
            try {
                CrearArchivo(lista);
            } catch (IOException ex) {
                Logger.getLogger(RecomendacionUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }
    }//GEN-LAST:event_btnRecomendarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         JFrame menu = new JFrame();
            menu.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textFieldAñoLanzamientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldAñoLanzamientoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if (!(Character.isDigit(c) || c ==KeyEvent.VK_BACKSPACE) || c==KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_textFieldAñoLanzamientoKeyTyped

    public void CrearArchivo (ArrayList<String> lista) throws IOException {
        String ruta = "src/Tests/Datos.txt";
        File file = new File(ruta);
        String rutaCompleta = file.getAbsolutePath();

        File archivo = new File(rutaCompleta);
        BufferedWriter bw;
        
        if(archivo.exists()) {
            FileReader fr = null;
            BufferedReader br = null;
            fr = new FileReader (archivo);
            br = new BufferedReader(fr);
            String linea;
         while((linea=br.readLine())!=null)
            lista.add(linea);
        }
        
            bw = new BufferedWriter(new FileWriter(archivo));
            for (int i = 0; i < lista.size(); i++) {
              bw.write(lista.get(i)+"\n");  
            }
        
        bw.close();
    }
    
    public static double Round(double valor, int numeroDecimales) {
        double parteEntera, resultado;
        resultado = valor;
        parteEntera = Math.floor(resultado);
        resultado=(resultado-parteEntera)*Math.pow(10, numeroDecimales);
        resultado=Math.round(resultado);
        resultado=(resultado/Math.pow(10, numeroDecimales))+parteEntera;
        return resultado;
    }
    
    public void Similitud (String Director, String Actor, String Genero, String Pais, String Año, String Idioma, String Color) {
        
        DataSetMovies data = new DataSetMovies();
        data.LeerArchivo(ruta);
        String tempo = "";
        
        Director = Director.replace(" ", "");
        Actor = Actor.replace(" ", "");
        Genero = Genero.replace(" ", "");
        Pais = Pais.replace(" ", "");
        Año = Año.replace(" ", "");
        Idioma = Idioma.replace(" ", "");
        Color = Color.replace(" ", "");
        
        double pesoDirector = 0.35;
        double pesoActor = 0.15;
        double pesoGenero = 0.40;
        double pesoPais = 0.20;
        double pesoAñoLanzamiento = 0.30;
        double pesoIdioma = 0.25;
        double pesoColor;
         
        String[] generosUsuario = Genero.split(",");
        String[] directorUsuario = Director.split(",");
        String[] actorUsuario = Actor.split(",");
        String[] paisUsuario = Pais.split(",");
        String[] añoUsuario = Año.split(",");
        
       
        for (int i = 0; i < data.director_name.size(); i++) {
            double similitud = 0.0;
            
            //COLOR
            if (Director.isEmpty()&&Actor.isEmpty()&&Genero.isEmpty()&&Pais.isEmpty()&&Año.isEmpty()) {
                if (Color.equals("Color")) {
                    tempo = data.color.get(i).replace(" ", "");
                    if (tempo.equals(Color)) {
                        //pesoColor = setPesoPorProbabilidad(data.color,Color);
                        pesoColor = 0.0;
                        similitud = similitud + pesoColor;
                    }
            }
            }
            if (Color.equals("BlackandWhite")) {
                tempo = data.color.get(i).replace(" ", "");
                if (tempo.equals(Color)) {
                    //pesoColor = setPesoPorProbabilidad(data.color,Color);
                    pesoColor = 1.0;
                    similitud = similitud + pesoColor;
                }
            }
            //IDIOMA
            if (data.language.get(i).toUpperCase().equals(Idioma.toUpperCase())) {
                //pesoIdioma = setPesoPorProbabilidad(data.language,Idioma);
                similitud = similitud + pesoIdioma;
            }
            //DIRECTOR
            for (String director : directorUsuario){
               tempo = data.director_name.get(i).replace(" ", "");
            if(tempo.toUpperCase().equals(director.toUpperCase())){
                //pesoDirector = setPesoPorProbabilidad(data.director_name,director);
                similitud = similitud + pesoDirector;
            }
            }
            //AÑO        
            for (String año : añoUsuario){
                if (año.equals("")) {
                    año="0";
                }
            if(data.title_year.get(i) == Integer.parseInt(año)){
                //pesoAñoLanzamiento = setPesoPorProbabilidadInteger(data.title_year,Integer.parseInt(año));
                similitud = similitud + pesoAñoLanzamiento;
            }
            }
            //ACTOR
            for (String actor : actorUsuario){
                tempo = data.actor_1_name.get(i).replace(" ", "");
            if(tempo.toUpperCase().equals(actor.toUpperCase())){
                //pesoActor = setPesoPorProbabilidad(data.actor_1_name,actor);
                similitud = similitud + pesoActor;
            }
            tempo = data.actor_2_name.get(i).replace(" ", "");
            if(tempo.toUpperCase().equals(actor.toUpperCase())){
                //pesoActor = setPesoPorProbabilidad(data.actor_2_name,actor);
                similitud = similitud + pesoActor;
            }
            tempo = data.actor_3_name.get(i).replace(" ", "");    
            if(tempo.toUpperCase().equals(actor.toUpperCase())){
                 //pesoActor = setPesoPorProbabilidad(data.actor_3_name,actor);
                similitud = similitud + pesoActor;
            }
            }
            //PAIS
            for (String pais : paisUsuario){
            tempo = data.country.get(i).replace(" ", "");
            if(tempo.toUpperCase().equals(pais.toUpperCase())){
                 //pesoPais = setPesoPorProbabilidad(data.country,pais);
                similitud = similitud + pesoPais;
            }
            }
            //GENEROS 
            ArrayList<String> generosMovie = new ArrayList<>();
            generosMovie = data.genres_by_movie.get(i);
            for (String genero : generosUsuario){
            if(generosMovie.contains(genero)){
                 //pesoGenero = setPesoPorProbabilidad(data.genres_by_movie.get(i),genero);
                similitud = similitud + pesoGenero;
            }
            }

            similitud = Round(similitud,4);
            listaSimilitud.add(similitud);

        }
        GetListaRecomendacion();
    }
    
    public void GetListaRecomendacion() {
        
        double rango1=0.0;
        double rango2=0.0;
        rango1 = getMax(listaSimilitud,1);
        rango2 = getMax(listaSimilitud,2);
        
        int contador = 2;
        if (rango2 == rango1) {
            while (true) {
            rango2 = getMax(listaSimilitud,contador);
                if (rango2 != rango1) {
                    break;
                } 
                contador++;
            }
        }
        contador = 0;
        for(double n: listaSimilitud)
        {
            if(Objects.equals(n, rango1)|| Objects.equals(n, rango2))                
            {
                listaRecomendacion.add(contador);                        
            }
            contador++;
        }
    }
    
    //Calculamos los pesos para el Content-Based Filtering por medio de la probabilidad del item en el data set
    public Double setPesoPorProbabilidad (ArrayList<String> lista, String valor) {
        double peso, numerador, denominador =0.0;
        int numeroTotal = lista.size();
        int numeroAciertos =0;
        String tempo ="";
        
        valor = valor.replace(" ", "");
        
        for (int i = 0; i < lista.size(); i++) {
            tempo = lista.get(i).replace(" ", "");
            if (tempo.toUpperCase().equals(valor.toUpperCase())) {
                numeroAciertos++;
            }
        }
        numerador = numeroAciertos;
        denominador = numeroTotal;
        peso = (numerador/denominador);
        return peso;
    }
    
    public Double setPesoPorProbabilidadInteger (ArrayList<Integer> lista, Integer valor) {
        double peso, numerador, denominador =0.0;
        int numeroTotal = lista.size();
        int numeroAciertos =0;       
       
        for (int i = 0; i < lista.size(); i++) {
            if (lista.get(i)==valor) {
                numeroAciertos++;
            }
        }
        numerador = numeroAciertos;
        denominador = numeroTotal;
        peso = (numerador/denominador);
        return peso;
    }
            
    public Double getMax (ArrayList lista, int n){
        ArrayList<Double> sortedlist = new ArrayList<>(lista); 
        Collections.sort(sortedlist); 
        return sortedlist.get(sortedlist.size()-n);
   }
    
    public Double getMin (ArrayList lista, int n){
        List<Double> sortedlist = new ArrayList<>(lista); 
        Collections.sort(sortedlist); 
        return sortedlist.get(n);
   }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecomendacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecomendacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecomendacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecomendacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecomendacionUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox boxAccion;
    private javax.swing.JCheckBox boxAnimacion;
    private javax.swing.JCheckBox boxAventura;
    private javax.swing.JCheckBox boxBiografia;
    private javax.swing.JCheckBox boxComedia;
    private javax.swing.JCheckBox boxCrimen;
    private javax.swing.JCheckBox boxDeporte;
    private javax.swing.JCheckBox boxDocumental;
    private javax.swing.JCheckBox boxDrama;
    private javax.swing.JCheckBox boxFamilia;
    private javax.swing.JCheckBox boxFantasia;
    private javax.swing.JCheckBox boxFiccion;
    private javax.swing.JCheckBox boxFilmNoir;
    private javax.swing.JCheckBox boxGameShow;
    private javax.swing.JCheckBox boxGuerra;
    private javax.swing.JCheckBox boxHistoria;
    private javax.swing.JCheckBox boxHorror;
    private javax.swing.JCheckBox boxMisterio;
    private javax.swing.JCheckBox boxMusica;
    private javax.swing.JCheckBox boxMusical;
    private javax.swing.JCheckBox boxNews;
    private javax.swing.JCheckBox boxRealityTV;
    private javax.swing.JCheckBox boxRomance;
    private javax.swing.JCheckBox boxShort;
    private javax.swing.JCheckBox boxSuspenso;
    private javax.swing.JCheckBox boxWestern;
    private javax.swing.JButton btnRecomendar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textFieldActor;
    private javax.swing.JTextField textFieldAñoLanzamiento;
    private javax.swing.JTextField textFieldPais;
    private javax.swing.JTextField txtFieldDirector;
    // End of variables declaration//GEN-END:variables
}
